[project]
site_name = "pyvolleydata"
site_description = "Load professional volleyball data as pandas DataFrames."
site_url = "https://ryanndu.github.io/pyvolleydata/"
repo_url = "https://github.com/ryanndu/pyvolleydata"
repo_name = "ryanndu/pyvolleydata"
nav = [
  { "Home" = "index.md" },
  { "API reference" = "reference.md" },
  { "Data dictionary" = "data-dictionary.md" },
  { "Changelog" = "changelog.md" },
  { "Analyzing a match" = "analyzing-a-match.md" },
]

[project.theme]
language = "en"
features = [
  "content.code.annotate",
  "content.code.copy",
  "navigation.footer",
  "navigation.instant",
  "navigation.sections",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
]

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.plugins.markdown-exec]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
show_root_heading = true
show_source = false
heading_level = 2

[project.markdown_extensions]
admonition = {}
attr_list = {}
md_in_html = {}
toc.permalink = true
pymdownx.details = {}
pymdownx.highlight.anchor_linenums = true
pymdownx.highlight.line_spans = "__span"
pymdownx.highlight.pygments_lang_class = true
pymdownx.inlinehilite = {}
pymdownx.superfences = {}
pymdownx.snippets.base_path = ["."]
pymdownx.snippets.check_paths = true